import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "es";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navbar
    "nav.howItWorks": "How It Works",
    "nav.poolTypes": "Pool Types",
    "nav.faqs": "FAQ",
    "nav.terms": "Terms",
    "nav.privacy": "Privacy",
    "nav.contact": "Contact",
    "nav.points": "Points System",
    "nav.playNow": "PLAY NOW!",

    // Hero
    "hero.title": "Matchpool",
    "hero.tagline": "Join pools, predict scores, climb the rankings",
    "hero.description": "Create or join private prediction pools for real football tournaments. Predict match scores, compete on rankings, and in Extreme pools change predictions after kick-off using coins.",
    "hero.cta1": "Access it now",
    "hero.cta2": "Explore Pool Types",

    // What is a Pool
    "whatIsPool.title": "What is a Prediction Pool?",
    "whatIsPool.subtitle": "A fun way to compete with friends by predicting football match results",
    "whatIsPool.feature1.title": "Compete with Friends",
    "whatIsPool.feature1.description": "Create or join private groups to predict match scores together",
    "whatIsPool.feature2.title": "Earn Points",
    "whatIsPool.feature2.description": "Accurate predictions earn points, climb the rankings to win!",
    "whatIsPool.feature3.title": "Real Tournaments",
    "whatIsPool.feature3.description": "Predict matches from actual football tournaments worldwide",
    "whatIsPool.mainDescription": "A prediction pool (or football pool) is a private group where friends compete by predicting match outcomes. Each correct prediction earns points, and rankings show who's the best predictor. It's all about bragging rights and friendly competition, no gambling, no real money, just pure football fun!",
    "whatIsPool.regionalTitle": "Known by Many Names",
    "whatIsPool.regionalSubtitle": "Across Latin America and beyond, prediction pools are a beloved tradition with different regional names:",
    "whatIsPool.polla.regions": "Northern South America",
    "whatIsPool.quiniela.regions": "Mexico, Central America & Caribbean",
    "whatIsPool.prode.regions": "Argentina & Uruguay",
    "whatIsPool.callout": "No matter what you call it...",
    "whatIsPool.calloutHighlight": "It's all about the thrill of predicting and competing!",

    // How It Works
    "howItWorks.title": "How It Works",
    "howItWorks.subtitle": "Get started with Matchpool in three simple steps",
    "howItWorks.step1.title": "Join or Create a Pool",
    "howItWorks.step1.description": "In the Pools section, tap 'Join' and enter a pool code, or tap 'Create', choose a tournament, name your pool, and pick the type (Standard, Full, or Extreme). Pools are private, share the code with friends.",
    "howItWorks.step2.title": "Make Predictions",
    "howItWorks.step2.description": "Open a pool and go to Matches. Tap an upcoming match and set your predicted score. In Full pools, predict goal scorers, assists, and cards too. Change anytime before kick-off (or during first half in Extreme pools using coins).",
    "howItWorks.step3.title": "Compete & Climb Rankings",
    "howItWorks.step3.description": "Each pool has a ranking. Points are awarded based on prediction accuracy, exact score earns the most. See your position, view other members' predictions after matches finish, and compete for the top spot!",
    "howItWorks.pointsCTA": "Check How Points Are Calculated",

    // Pool Types Overview (brief on homepage)
    "poolTypes.title": "Pool Types",
    "poolTypes.subtitle": "Choose the perfect pool type for your group",
    "poolTypes.standard.title": "Standard Pool",
    "poolTypes.standard.description": "Predice solo marcadores de partidos. Simple y rápido, perfecto para competencia casual.",
    "poolTypes.full.title": "Pool Full",
    "poolTypes.full.description": "Marcadores de partidos más predicciones de jugadores: goleadores, asistencias, tarjetas amarillas y rojas.",
    "poolTypes.extreme.title": "Extreme Pool",
    "poolTypes.extreme.description": "Change match scores after kick-off (until first half ends) by spending coins. More dynamic gameplay!",
    "poolTypes.viewDetails": "View Full Details",

    // Pool Types Detail Page
    "poolTypesDetail.title": "Pool Types Explained",
    "poolTypesDetail.subtitle": "Everything you need to know about Standard, Full, and Extreme pools",
    
    "poolTypesDetail.standard.title": "Standard Pool",
    "poolTypesDetail.standard.what": "What it is",
    "poolTypesDetail.standard.whatDesc": "Predict only match scores (e.g., 2–1, 0–0). No goal scorers, assists, or cards.",
    "poolTypesDetail.standard.features": "Key Features",
    "poolTypesDetail.standard.feature1": "Match scores only",
    "poolTypesDetail.standard.feature2": "No coins required",
    "poolTypesDetail.standard.feature3": "Predictions lock at kick-off",
    "poolTypesDetail.standard.feature4": "Perfect for simple, fast pools",
    "poolTypesDetail.standard.useCase": "Best for groups who want straightforward score predictions without extra complexity.",

    "poolTypesDetail.full.title": "Full Pool",
    "poolTypesDetail.full.what": "What it is",
    "poolTypesDetail.full.whatDesc": "Match scores plus player predictions: goal scorers, assists, yellow cards, and red cards.",
    "poolTypesDetail.full.features": "Key Features",
    "poolTypesDetail.full.feature1": "Match scores + player predictions",
    "poolTypesDetail.full.feature2": "Predict goal scorers, assists, cards",
    "poolTypesDetail.full.feature3": "Random button for quick player selection",
    "poolTypesDetail.full.feature4": "No coins; predictions lock at kick-off",
    "poolTypesDetail.full.useCase": "Deeper gameplay for users who want to predict scorers and cards as well.",
    "poolTypesDetail.full.random": "Random Button",
    "poolTypesDetail.full.randomDesc": "For each slot (e.g., first goal scorer), tap 'Random' to assign a random player from the match squad. You can still change it manually before kick-off.",

    "poolTypesDetail.extreme.title": "Extreme Pool (Coin-Based)",
    "poolTypesDetail.extreme.what": "What it is",
    "poolTypesDetail.extreme.whatDesc": "Same as Standard or Full pools, plus the ability to change predicted match scores after kick-off until the end of the first half by spending coins.",
    "poolTypesDetail.extreme.features": "Key Features",
    "poolTypesDetail.extreme.feature1": "Change scores after kick-off (until first half ends)",
    "poolTypesDetail.extreme.feature2": "Each change costs 5 coins",
    "poolTypesDetail.extreme.feature3": "Limited changes per tournament (e.g., 5 in group stage, 2 in knockout)",
    "poolTypesDetail.extreme.feature4": "Receive 70% of points for changed predictions",
    "poolTypesDetail.extreme.coins": "How Coins Work",
    "poolTypesDetail.extreme.coinsDesc": "Coins are required only in Extreme pools to change match scores after kick-off.",
    "poolTypesDetail.extreme.cost": "Cost: 5 coins per score change",
    "poolTypesDetail.extreme.earning": "Earning Coins: Watch short video ads in the app (Coins Bank). Limited ads with cooldown periods (e.g., 15 minutes).",
    "poolTypesDetail.extreme.future": "Future: A coins store may be added to purchase coins.",
    "poolTypesDetail.extreme.limits": "Limits & Trade-offs",
    "poolTypesDetail.extreme.limitsDesc": "Only a limited number of matches can be changed per tournament phase (e.g., 5 in group stage, 2 in knockout). Changes are only allowed until the first half ends. If you use a change, you receive 70% of the points you would have earned for that match (not 100%).",
    "poolTypesDetail.extreme.useCase": "Perfect for dynamic pools where users can react to live action, with clear costs and trade-offs.",

    // FAQ
    "faqs.title": "Frequently Asked Questions",
    "faqs.subtitle": "Everything you need to know about Matchpool",
    "faqs.q1": "What is a pool?",
    "faqs.a1": "A pool is a group where users compete by predicting match scores and player performances. Each pool is tied to a specific tournament, and members earn points based on how accurate their predictions are.",
    "faqs.q2": "How do I join a pool?",
    "faqs.a2": "You need a pool code from the pool creator. Go to the Pools section, tap 'Join', enter the code, and you'll be added to the pool. You can then start making predictions for upcoming matches.",
    "faqs.q3": "How do I create a pool?",
    "faqs.a3": "In the Pools section, tap 'Create', select a tournament, and choose a name for your pool. You can create a Standard pool (match scores only) or a Full pool (match scores plus player predictions: goal scorers, assists, yellow and red cards). If you enable the Extreme Pool option, you and your friends will be able to change match scores after kick-off (until the end of the first half) by spending coins. Pools are private: share the generated code so others can join.",
    "faqs.q4": "When can I make predictions?",
    "faqs.a4": "You can make or change predictions anytime before a match starts. Once a match begins, predictions are locked and cannot be modified (except in Extreme pools, where you can change the score until the end of the first half by spending coins). Submit your predictions before the match deadline.",
    "faqs.q5": "How do points work?",
    "faqs.a5": "Points are awarded based on the accuracy of your predictions. Exact score predictions earn the most points. The ranking in each pool shows all members ordered by their total points. Points are calculated automatically after each match ends.",
    "faqs.q6": "What are player predictions?",
    "faqs.a6": "Some pools (Full pools) allow you to predict specific player actions like goal scorers, assists, yellow cards, and red cards in addition to match scores. These predictions can earn you extra points. Not all pools have this feature enabled.",
    "faqs.q7": "Can I change my predictions?",
    "faqs.a7": "Yes, you can change your predictions as many times as you want before a match starts. Once the match begins, predictions are locked—unless the pool is an Extreme pool. In Extreme pools you can change the score of a match until the end of the first half by spending 5 coins per change. You can change only a limited number of match scores per tournament (e.g. 5 in group stage, 2 in knockout). Always double-check your predictions before the deadline.",
    "faqs.q8": "What is an Extreme pool and how does it work?",
    "faqs.a8": "An Extreme pool lets you change your predicted score for a match after it has already started, until the end of the first half. Each change costs 5 coins. There is a limit to how many matches you can change per tournament (e.g. 5 in group stage, 2 in knockout). If you use a change, you do not get the full points for that match: you receive 70% of the points you would have earned. Coins can be earned by watching short video ads in the app or (when available) purchased in the Coins store.",
    "faqs.q9": "How does the Random button work for player predictions in Full pool?",
    "faqs.a9": "In Full pools, you can predict goal scorers, assists, and cards. For each slot (e.g. first goal scorer, yellow card), you can tap the 'Random' button to have the app assign a random player from the match squad to that slot. You can still change the selection manually before the match starts.",
    "faqs.q10": "How can I get coins?",
    "faqs.a10": "You can earn coins by watching short video ads in the app: go to the Coins Bank (or Coins section in your profile) and tap 'Watch Ad to Earn Coins'. You can watch a limited number of ads in a row, then you need to wait before watching more. A coins store where you can buy coins may be added in the future.",
    "faqs.q11": "What happens if I predict the winner of the tournament?",
    "faqs.a11": "You can pick the team you think will win the tournament. If your pick wins the tournament, you earn 40 bonus points that are added to your final score in the pool. This is in addition to the points you get from match and player predictions.",

    // Terms
    "terms.title": "Terms & Conditions",
    "terms.updated": "Last updated: May 7, 2026",
    "terms.owner": "BIGTHOR DEVELOPMENT",
    "terms.intro": "By accessing or using the Matchpool mobile application ('App'), you agree to these Terms & Conditions.",
    "terms.section1.title": "1. Service Description",
    "terms.section1.point1": "The App allows users to create or join private prediction pools related to real football tournaments and compete by predicting match outcomes.",
    "terms.section1.point2": "The App is for entertainment only. It does not involve gambling, betting, or real-money wagering.",
    "terms.section1.point3": "The App is supported by ads served by Google Mobile Ads (AdMob). By using the App you acknowledge that ads may be displayed and that ad-related data may be processed by Google and its advertising partners as described in the Privacy Policy.",
    "terms.section2.title": "2. User Accounts",
    "terms.section2.point1": "Accurate registration information required",
    "terms.section2.point2": "Email verification required",
    "terms.section2.point3": "You are responsible for account security",
    "terms.section2.point4": "No account sharing",
    "terms.section2.point5": "We may suspend or terminate accounts for violations",
    "terms.section3.title": "3. Pools & Administration",
    "terms.section3.point1": "Pools are private and accessed via invite codes",
    "terms.section3.point2": "Pool admins may manage members",
    "terms.section3.point3": "We are not responsible for disputes between pool members",
    "terms.section4.title": "4. Predictions & Scoring",
    "terms.section4.point1": "Predictions must be submitted before match kickoff",
    "terms.section4.point2": "Predictions lock at kickoff",
    "terms.section4.point3": "Scoring is automatic",
    "terms.section4.point4": "Match results based on official final scores (extra time included, penalty shootouts excluded)",
    "terms.section4.point5": "Scoring decisions are final",
    "terms.section5.title": "5. Fair Use",
    "terms.section5.point1": "No bypassing prediction locks",
    "terms.section5.point2": "No exploiting bugs",
    "terms.section5.point3": "No abusing pool mechanics or invite codes",
    "terms.section5.point4": "No interfering with backend services",
    "terms.section5.point5": "Violations may result in suspension or termination",
    "terms.section6.title": "6. Third-Party APIs & External Data",
    "terms.section6.desc": "The App relies on third-party APIs and services to provide match, team, player, and related data, as well as other features (for example authentication, email delivery, or advertising). Correct operation of the App—including loading data, scoring, rankings, and notifications—depends on the availability, performance, and stability of those third-party services. Outages, rate limits, errors, or changes by providers may cause delays, incomplete data, or temporary loss of functionality. We do not guarantee the accuracy, timeliness, or uninterrupted availability of third-party data or services.",
    "terms.section7.title": "7. Availability",
    "terms.section7.desc": "Service provided 'as available'. No guarantee of uninterrupted or error-free service.",
    "terms.section8.title": "8. Intellectual Property",
    "terms.section8.desc": "All content, branding, designs, and software owned by BIGTHOR DEVELOPMENT. Unauthorized copying or reverse engineering prohibited.",
    "terms.section9.title": "9. Limitation of Liability",
    "terms.section9.desc": "App provided 'as is'. We are not liable for missed predictions, incorrect rankings, or user disputes. Liability limited as permitted by law.",
    "terms.section10.title": "10. Termination",
    "terms.section10.desc": "You may delete your account at any time. We may suspend or terminate for violations or misuse.",
    "terms.section11.title": "11. Governing Law",
    "terms.section11.desc": "Laws of the Province of Quebec and applicable federal laws of Canada.",
    "terms.section12.title": "12. Contact",
    "terms.section12.desc": "BIGTHOR DEVELOPMENT — Email:",

    // Privacy
    "privacy.title": "Privacy Policy",
    "privacy.updated": "Last updated: May 7, 2026",
    "privacy.owner": "BIGTHOR DEVELOPMENT",
    "privacy.intro": "This Privacy Policy explains how BIGTHOR DEVELOPMENT collects, uses, stores, and protects your information when you use the Matchpool mobile application. We use your information to provide Matchpool's core features and improve your experience in the app.",
    "privacy.section1.title": "1. Information We Collect",
    "privacy.section1.point1": "Account information: name, email address, profile details, encrypted password (email/password login), and Google account identifier (if Google Sign-In)",
    "privacy.section1.point2": "Usage data: pools created or joined, predictions submitted, match interactions, rankings and scores, screens viewed, actions taken, and error logs",
    "privacy.section1.point3": "Technical data: device type and OS, app version, language, approximate IP address, in-app events, and performance data",
    "privacy.section1.point4": "Advertising identifiers: the Advertising ID used by Google Mobile Ads (AdMob) to serve and measure ads",
    "privacy.section1.point5": "We do not collect sensitive personal data such as government IDs, payment details, or precise location",
    "privacy.section2.title": "2. How We Use Your Information",
    "privacy.section2.desc": "When you create an account or sign in, we process data such as your name, email address, and profile details to authenticate you, keep you signed in, and enable you to create or join matches, manage your profile, and access app features. We also use app usage data (such as screens viewed, actions taken, and error logs) to diagnose issues, improve stability, enhance features, generate rankings and statistics, send transactional emails, and detect abuse. We do not sell your personal information.",
    "privacy.section3.title": "3. Emails & Notifications",
    "privacy.section3.desc": "Email verification (6-digit code), password reset, match reminders (only if no prediction submitted). No marketing emails without explicit consent.",
    "privacy.section4.title": "4. Advertising & Mobile Ads (AdMob)",
    "privacy.section4.desc": "Matchpool integrates Google Mobile Ads (AdMob) to display ads. AdMob may collect and use device identifiers such as the Advertising ID, along with technical information (for example, approximate IP address, device type, language, in-app events, and performance data) to serve ads, measure ad performance, prevent fraud and abuse, and generate analytics and reporting. This information may be processed by Google and its advertising partners according to their policies. For details, see Google's Privacy Policy and the AdMob policies. Where applicable, you can reset or limit your Advertising ID through your device settings.",
    "privacy.section5.title": "5. Data Sharing",
    "privacy.section5.desc": "We do not sell your personal information. We only share it with service providers needed to operate the app — such as advertising partners (Google AdMob), email delivery providers, football data API providers, and infrastructure services — or when required by law.",
    "privacy.section6.title": "6. Data Storage & Security",
    "privacy.section6.desc": "Data in secured database; passwords hashed; tokens time-limited; role-based access; reasonable safeguards applied.",
    "privacy.section7.title": "7. Data Retention",
    "privacy.section7.desc": "Account data retained while active; you may request deletion; some anonymized/aggregated data may be retained.",
    "privacy.section8.title": "8. Your Rights",
    "privacy.section8.desc": "Access, correction, deletion, withdraw consent. Contact us for requests.",
    "privacy.section9.title": "9. Children's Privacy",
    "privacy.section9.desc": "App not intended for users under 13. We do not knowingly collect data from children.",
    "privacy.section10.title": "10. Changes to This Policy",
    "privacy.section10.desc": "Policy may be updated. 'Last updated' date will change.",
    "privacy.section11.title": "11. Contact",
    "privacy.section11.desc": "BIGTHOR DEVELOPMENT — Email:",

    // Contact
    "contact.title": "Get in Touch",
    "contact.subtitle": "Have questions or feedback? We'd love to hear from you.",
    "contact.email": "Email us at",
    "contact.owner": "Owned by BIGTHOR DEVELOPMENT",
    "contact.form.name": "Name",
    "contact.form.email": "Email",
    "contact.form.message": "Message",
    "contact.form.namePlaceholder": "Your name",
    "contact.form.emailPlaceholder": "your.email@example.com",
    "contact.form.messagePlaceholder": "Tell us what's on your mind...",
    "contact.form.submit": "Send Message",
    "contact.form.success": "Message Sent!",
    "contact.form.successMessage": "We'll get back to you soon.",

    // Social Competition
    "social.title": "Compete & Share with Friends",
    "social.subtitle": "It's not just about predictions, it's about bragging rights!",
    "social.description": "See where you rank against your friends in real-time. Share your victories when you're on top, or challenge yourself to climb back up when you're trailing. Every prediction counts!",
    "social.first.title": "On Top of the World",
    "social.first.description": "When you're #1, let everyone know! Share your winning streak.",
    "social.last.title": "Time for a Comeback",
    "social.last.description": "Last place? No worries, the next match is your chance to rise!",
    "social.shareFeature": "Share your ranking with friends and keep the competition alive!",

    // Footer
    "footer.tagline": "Join pools, predict scores, climb the rankings.",
    "footer.quickLinks": "Quick Links",
    "footer.legal": "Legal",
    "footer.rights": "© 2026 Matchpool by BIGTHOR DEVELOPMENT. All rights reserved.",
    "footer.entertainment": "For entertainment only. No gambling or real-money wagering.",

    // Points Page
    "points.title": "How Points Are Calculated",
    "points.subtitle": "Understand the scoring system to maximize your predictions and climb the rankings",
    
    "points.overview.title": "Overview",
    "points.overview.description": "Each prediction earns points through a three-step process: (1) Base Score (1-10 scale based on accuracy), (2) Coin Deduction (if you changed predictions after kick-off), and (3) Stage Multiplier (knockout matches are worth double). The tournament winner prediction is separate and awards 30 points.",
    
    "points.step1.title": "Step 1: Base Score (1-10 Scale)",
    "points.step1.exactScore.title": "Exact Score Match",
    "points.step1.exactScore.description": "Perfect prediction of the final score",
    "points.step1.exactScore.example": "Example: You predict 2-1, result is 2-1 → 5 points",
    "points.step1.correctResult.title": "Correct Result",
    "points.step1.correctResult.description": "Right winner or draw (but wrong score)",
    "points.step1.correctResult.example": "Example: You predict 2-0, result is 3-1 (both wins) → 2 points",
    "points.step1.goalDifference.title": "Goal Difference",
    "points.step1.goalDifference.description": "Same margin, non-zero & same sign",
    "points.step1.goalDifference.example": "Example: You predict 3-1 (+2), result is 2-0 (+2) → 1 point",
    "points.step1.homeGoal.title": "Home Goal Count",
    "points.step1.homeGoal.description": "Correct home team goals",
    "points.step1.homeGoal.example": "Example: You predict 2-1, result is 2-0 → 1 point for home",
    "points.step1.awayGoal.title": "Away Goal Count",
    "points.step1.awayGoal.description": "Correct away team goals",
    "points.step1.awayGoal.example": "Example: You predict 2-1, result is 3-1 → 1 point for away",
    "points.step1.playerEvents.title": "Player Events (Pro Pools Only)",
    "points.step1.playerEvents.description": "Correct scorer, assist, yellow or red card",
    "points.step1.playerEvents.example": "Example: You predict Messi scores, Messi scores → 1 point per event",
    "points.step1.range.title": "Total Base Score Range",
    "points.step1.range.description": "Your base score ranges from 0 to 10 points depending on prediction accuracy. Points can stack (exact score automatically includes result, goals, etc.).",
    
    "points.step2.title": "Step 2: Coin Deduction (If Applicable)",
    "points.step2.subtitle": "Changed After Kick-Off?",
    "points.step2.description": "In pools with coins, if you change your prediction after the match starts, points are deducted from your base score before applying the stage multiplier.",
    "points.step2.highScore.title": "High Base Score (6-10)",
    "points.step2.highScore.description": "Subtract 2 points",
    "points.step2.highScore.example": "Example: 7 base points → 7 - 2 = 5 points",
    "points.step2.lowScore.title": "Low Base Score (1-5)",
    "points.step2.lowScore.description": "Subtract 1 point",
    "points.step2.lowScore.example": "Example: 3 base points → 3 - 1 = 2 points",
    "points.step2.note.title": "Important:",
    "points.step2.note.description": "Score never goes below 0. If unchanged, no deduction applies.",
    
    "points.step3.title": "Step 3: Stage Multiplier",
    "points.step3.groupStage.title": "Group Stage",
    "points.step3.groupStage.description": "No multiplier applied",
    "points.step3.groupStage.example": "Example: 5 points × 1 = 5 points",
    "points.step3.knockout.title": "Knockout Stage",
    "points.step3.knockout.description": "Points are doubled",
    "points.step3.knockout.example": "Example: 5 points × 2 = 10 points",
    
    "points.tournamentWinner.title": "Tournament Winner Prediction",
    "points.tournamentWinner.points": "points",
    "points.tournamentWinner.description": "When the tournament ends, every user who correctly predicted the winner receives a bonus.",
    "points.tournamentWinner.note.title": "Note:",
    "points.tournamentWinner.note.description": "No stage multiplier or coin deduction applies to this bonus.",
    
    "points.example.title": "Example Calculation",
    "points.example.scenario.title": "Scenario:",
    "points.example.scenario.description": "Knockout match. You predicted 2-1, changed it with coins. Actual result: 3-1. Base score: 5 points (correct result + home goal + away goal).",
    "points.example.calculation.title": "Calculation:",
    "points.example.calculation.step1": "Base Score: Correct result (2) + away goal (1) + correct goal difference (1) + home team won (included in result)",
    "points.example.calculation.step1Result": "Base Score = 4 points",
    "points.example.calculation.step2": "Coin Deduction: Base is 4 (low range), so subtract 1",
    "points.example.calculation.step2Result": "After Deduction = 3 points",
    "points.example.calculation.step3": "Stage Multiplier: Knockout stage, multiply by 2",
    "points.example.calculation.step3Result": "Final Points = 3 × 2 = 6 points",
    "points.example.final.title": "Final Score:",
    "points.example.final.result": "6 points",
    
    "points.poolTypes.title": "How Pool Types Affect Scoring",
    "points.poolTypes.regular.title": "Regular Pools",
    "points.poolTypes.regular.feature1": "Score-based points only",
    "points.poolTypes.regular.feature2": "No player event predictions",
    "points.poolTypes.pro.title": "Pro Pools",
    "points.poolTypes.pro.feature1": "Score-based points",
    "points.poolTypes.pro.feature2": "+ Player events (scorers, assists, cards)",
    "points.poolTypes.coins.title": "Pools With Coins",
    "points.poolTypes.coins.feature1": "Can change predictions after kick-off",
    "points.poolTypes.coins.feature2": "Coin deduction applies before stage multiplier",
  },
  es: {
    // Navbar
    "nav.howItWorks": "Cómo Funciona",
    "nav.poolTypes": "Tipos de Pools",
    "nav.faqs": "Preguntas Frecuentes",
    "nav.terms": "Términos",
    "nav.privacy": "Privacidad",
    "nav.contact": "Contacto",
    "nav.points": "Sistema de Puntos",
    "nav.playNow": "¡JUEGA AHORA!",

    // Hero
    "hero.title": "Matchpool",
    "hero.tagline": "Únete a pools, predice marcadores, escala en las clasificaciones",
    "hero.description": "Crea o únete a pools privados de predicción para torneos de fútbol reales. Predice marcadores de partidos, compite en las clasificaciones y en pools Extreme cambia predicciones después del inicio usando monedas.",
    "hero.cta1": "Accede ahora",
    "hero.cta2": "Explora Tipos de Pools",

    // What is a Pool
    "whatIsPool.title": "¿Qué es un Pool de Predicción?",
    "whatIsPool.subtitle": "Una forma divertida de competir con amigos prediciendo resultados de partidos de fútbol",
    "whatIsPool.feature1.title": "Compétencia con Amigos",
    "whatIsPool.feature1.description": "Crea o únete a grupos privados para predecir marcadores de partidos juntos",
    "whatIsPool.feature2.title": "Gana Puntos",
    "whatIsPool.feature2.description": "Predicciones precisas ganan puntos, escala en las clasificaciones para ganar!",
    "whatIsPool.feature3.title": "Torneos Reales",
    "whatIsPool.feature3.description": "Predice partidos de torneos de fútbol reales de todo el mundo",
    "whatIsPool.mainDescription": "Un pool de predicción (o pool de fútbol) es un grupo privado donde amigos compiten prediciendo resultados de partidos. Cada predicción correcta gana puntos, y las clasificaciones muestran quién es el mejor predictor. Todo es sobre derechos de presumir y competencia amistosa, sin apuestas, sin dinero real, solo pura diversión de fútbol!",
    "whatIsPool.regionalTitle": "Conocido por Muchos Nombres",
    "whatIsPool.regionalSubtitle": "A lo largo de América Latina y más allá, los pools de predicción son una tradición querida con nombres regionales diferentes:",
    "whatIsPool.polla.regions": "América del Sur Norte",
    "whatIsPool.quiniela.regions": "México, Centroamérica y Caribe",
    "whatIsPool.prode.regions": "Argentina y Uruguay",
    "whatIsPool.callout": "No importa cómo lo llames...",
    "whatIsPool.calloutHighlight": "¡Todo es sobre la emoción de predecir y competir!",

    // How It Works
    "howItWorks.title": "Cómo Funciona",
    "howItWorks.subtitle": "Comienza con Matchpool en tres simples pasos",
    "howItWorks.step1.title": "Únete o Crea un Pool",
    "howItWorks.step1.description": "En la sección Pools, toca 'Unirse' e ingresa un código de pool, o toca 'Crear', elige un torneo, nombra tu pool y selecciona el tipo (Standard, Full o Extreme). Los pools son privados, comparte el código con amigos.",
    "howItWorks.step2.title": "Haz Predicciones",
    "howItWorks.step2.description": "Abre un pool y ve a Partidos. Toca un partido próximo y establece tu marcador predicho. En pools Full, predice goleadores, asistencias y tarjetas también. Cambia en cualquier momento antes del inicio (o durante el primer tiempo en pools Extreme usando monedas).",
    "howItWorks.step3.title": "Compite y Escala en las Clasificaciones",
    "howItWorks.step3.description": "Cada pool tiene una clasificación. Los puntos se otorgan según la precisión de la predicción, el marcador exacto gana más. ¡Ve tu posición, mira las predicciones de otros miembros después de que terminen los partidos y compite por el primer lugar!",
    "howItWorks.pointsCTA": "Revisa Cómo Se Calculan los Puntos",

    // Pool Types Overview (brief on homepage)
    "poolTypes.title": "Tipos de Pools",
    "poolTypes.subtitle": "Elige el tipo de pool perfecto para tu grupo",
    "poolTypes.standard.title": "Pool Standard",
    "poolTypes.standard.description": "Predice solo marcadores de partidos. Simple y rápido, perfecto para competencia casual.",
    "poolTypes.full.title": "Pool Full",
    "poolTypes.full.description": "Marcadores de partidos más predicciones de jugadores: goleadores, asistencias, tarjetas amarillas y rojas.",
    "poolTypes.extreme.title": "Pool Extreme",
    "poolTypes.extreme.description": "Cambia marcadores de partidos después del inicio (hasta el final del primer tiempo) gastando monedas. ¡Juego más dinámico!",
    "poolTypes.viewDetails": "Ver Detalles Completos",

    // Pool Types Detail Page
    "poolTypesDetail.title": "Tipos de Pools Explicados",
    "poolTypesDetail.subtitle": "Todo lo que necesitas saber sobre pools Standard, Full y Extreme",
    
    "poolTypesDetail.standard.title": "Pool Standard",
    "poolTypesDetail.standard.what": "Qué es",
    "poolTypesDetail.standard.whatDesc": "Predice solo marcadores de partidos (ej., 2–1, 0–0). Sin goleadores, asistencias o tarjetas.",
    "poolTypesDetail.standard.features": "Características Clave",
    "poolTypesDetail.standard.feature1": "Solo marcadores de partidos",
    "poolTypesDetail.standard.feature2": "No se requieren monedas",
    "poolTypesDetail.standard.feature3": "Las predicciones se bloquean al inicio",
    "poolTypesDetail.standard.feature4": "Perfecto para pools simples y rápidos",
    "poolTypesDetail.standard.useCase": "Mejor para grupos que quieren predicciones de marcadores sencillas sin complejidad adicional.",

    "poolTypesDetail.full.title": "Pool Full",
    "poolTypesDetail.full.what": "Qué es",
    "poolTypesDetail.full.whatDesc": "Marcadores de partidos más predicciones de jugadores: goleadores, asistencias, tarjetas amarillas y tarjetas rojas.",
    "poolTypesDetail.full.features": "Características Clave",
    "poolTypesDetail.full.feature1": "Marcadores de partidos + predicciones de jugadores",
    "poolTypesDetail.full.feature2": "Predice goleadores, asistencias, tarjetas",
    "poolTypesDetail.full.feature3": "Botón aleatorio para selección rápida de jugadores",
    "poolTypesDetail.full.feature4": "Sin monedas; predicciones se bloquean al inicio",
    "poolTypesDetail.full.useCase": "Juego más profundo para usuarios que también quieren predecir goleadores y tarjetas.",
    "poolTypesDetail.full.random": "Botón Aleatorio",
    "poolTypesDetail.full.randomDesc": "Para cada espacio (ej., primer goleador), toca 'Aleatorio' para asignar un jugador aleatorio de la plantilla del partido. Aún puedes cambiarlo manualmente antes del inicio.",

    "poolTypesDetail.extreme.title": "Pool Extreme (Basado en Monedas)",
    "poolTypesDetail.extreme.what": "Qué es",
    "poolTypesDetail.extreme.whatDesc": "Igual que pools Standard o Full, más la capacidad de cambiar marcadores de partidos predichos después del inicio hasta el final del primer tiempo gastando monedas.",
    "poolTypesDetail.extreme.features": "Características Clave",
    "poolTypesDetail.extreme.feature1": "Cambia marcadores después del inicio (hasta el final del primer tiempo)",
    "poolTypesDetail.extreme.feature2": "Cada cambio cuesta 5 monedas",
    "poolTypesDetail.extreme.feature3": "Cambios limitados por torneo (ej., 5 en fase de grupos, 2 en eliminatorias)",
    "poolTypesDetail.extreme.feature4": "Recibe 70% de puntos por predicciones cambiadas",
    "poolTypesDetail.extreme.coins": "Cómo Funcionan las Monedas",
    "poolTypesDetail.extreme.coinsDesc": "Las monedas se requieren solo en pools Extreme para cambiar marcadores de partidos después del inicio.",
    "poolTypesDetail.extreme.cost": "Costo: 5 monedas por cambio de marcador",
    "poolTypesDetail.extreme.earning": "Ganar Monedas: Mira anuncios de video cortos en la app (Banco de Monedas). Anuncios limitados con períodos de espera (ej., 15 minutos).",
    "poolTypesDetail.extreme.future": "Futuro: Puede agregarse una tienda de monedas para comprar monedas.",
    "poolTypesDetail.extreme.limits": "Límites y Compromisos",
    "poolTypesDetail.extreme.limitsDesc": "Solo un número limitado de partidos puede cambiarse por fase del torneo (ej., 5 en fase de grupos, 2 en eliminatorias). Los cambios solo se permiten hasta el final del primer tiempo. Si usas un cambio, recibes 70% de los puntos que habrías ganado por ese partido (no 100%).",
    "poolTypesDetail.extreme.useCase": "Perfecto para pools dinámicos donde los usuarios pueden reaccionar a la acción en vivo, con costos y compromisos claros.",

    // FAQ
    "faqs.title": "Preguntas Frecuentes",
    "faqs.subtitle": "Todo lo que necesitas saber sobre Matchpool",
    "faqs.q1": "¿Qué es un pool?",
    "faqs.a1": "Un pool es un grupo donde los usuarios compiten prediciendo marcadores de partidos y rendimientos de jugadores. Cada pool está vinculado a un torneo específico, y los miembros ganan puntos según la precisión de sus predicciones.",
    "faqs.q2": "¿Cómo me uno a un pool?",
    "faqs.a2": "Necesitas un código de pool del creador del pool. Ve a la sección Pools, toca 'Unirse', ingresa el código y serás agregado al pool. Luego puedes comenzar a hacer predicciones para los próximos partidos.",
    "faqs.q3": "¿Cómo creo un pool?",
    "faqs.a3": "En la sección Pools, toca 'Crear', selecciona un torneo y elige un nombre para tu pool. Puedes crear un pool Standard (solo marcadores de partidos) o un pool Full (marcadores de partidos más predicciones de jugadores: goleadores, asistencias, tarjetas amarillas y rojas). Si habilitas la opción Pool Extreme, tú y tus amigos podrán cambiar marcadores de partidos después del inicio (hasta el final del primer tiempo) gastando monedas. Los pools son privados: comparte el código generado para que otros se unan.",
    "faqs.q4": "¿Cuándo puedo hacer predicciones?",
    "faqs.a4": "Puedes hacer o cambiar predicciones en cualquier momento antes de que comience un partido. Una vez que comienza el partido, las predicciones se bloquean y no pueden modificarse (excepto en pools Extreme, donde puedes cambiar el marcador hasta el final del primer tiempo gastando monedas). Envía tus predicciones antes de la fecha límite del partido.",
    "faqs.q5": "¿Cómo funcionan los puntos?",
    "faqs.a5": "Los puntos se otorgan según la precisión de tus predicciones. Las predicciones de marcador exacto ganan más puntos. La clasificación en cada pool muestra todos los miembros ordenados por sus puntos totales. Los puntos se calculan automáticamente después de que termina cada partido.",
    "faqs.q6": "¿Qué son las predicciones de jugadores?",
    "faqs.a6": "Algunos pools (pools Full) te permiten predecir acciones específicas de jugadores como goleadores, asistencias, tarjetas amarillas y tarjetas rojas además de marcadores de partidos. Estas predicciones pueden hacerte ganar puntos extra. No todos los pools tienen esta función habilitada.",
    "faqs.q7": "¿Puedo cambiar mis predicciones?",
    "faqs.a7": "Sí, puedes cambiar tus predicciones tantas veces como quieras antes de que comience un partido. Una vez que comienza el partido, las predicciones se bloquean—a menos que el pool sea un pool Extreme. En pools Extreme puedes cambiar el marcador de un partido hasta el final del primer tiempo gastando 5 monedas por cambio. Solo puedes cambiar un número limitado de marcadores de partidos por torneo (ej. 5 en fase de grupos, 2 en eliminatorias). Siempre verifica tus predicciones antes de la fecha límite.",
    "faqs.q8": "¿Qué es un pool Extreme y cómo funciona?",
    "faqs.a8": "Un pool Extreme te permite cambiar tu marcador predicho para un partido después de que ya haya comenzado, hasta el final del primer tiempo. Cada cambio cuesta 5 monedas. Hay un límite de cuántos partidos puedes cambiar por torneo (ej. 5 en fase de grupos, 2 en eliminatorias). Si usas un cambio, no obtienes los puntos completos para ese partido: recibes 70% de los puntos que habrías ganado. Las monedas pueden ganarse viendo anuncios de video cortos en la app o (cuando esté disponible) comprarse en la tienda de monedas.",
    "faqs.q9": "¿Cómo funciona el botón Aleatorio para predicciones de jugadores en pool Full?",
    "faqs.a9": "En pools Full, puedes predecir goleadores, asistencias y tarjetas. Para cada espacio (ej. primer goleador, tarjeta amarilla), puedes tocar el botón 'Aleatorio' para que la app asigne un jugador aleatorio de la plantilla del partido a ese espacio. Aún puedes cambiar la selección manualmente antes de que comience el partido.",
    "faqs.q10": "¿Cómo puedo obtener monedas?",
    "faqs.a10": "Puedes ganar monedas viendo anuncios de video cortos en la app: ve al Banco de Monedas (o sección de Monedas en tu perfil) y toca 'Ver Anuncio para Ganar Monedas'. Puedes ver un número limitado de anuncios seguidos, luego necesitas esperar antes de ver más. Puede agregarse una tienda de monedas donde puedas comprar monedas en el futuro.",
    "faqs.q11": "¿Qué pasa si predigo el ganador del torneo?",
    "faqs.a11": "Puedes elegir el equipo que crees que ganará el torneo. Si tu elección gana el torneo, ganas 40 puntos de bonificación que se agregan a tu puntuación final en el pool. Esto es además de los puntos que obtienes de las predicciones de partidos y jugadores.",

    // Terms
    "terms.title": "Términos y Condiciones",
    "terms.updated": "Última actualización: 7 de mayo de 2026",
    "terms.owner": "BIGTHOR DEVELOPMENT",
    "terms.intro": "Al acceder o usar la aplicación móvil Matchpool ('App'), aceptas estos Términos y Condiciones.",
    "terms.section1.title": "1. Descripción del Servicio",
    "terms.section1.point1": "La App permite a los usuarios crear o unirse a pools privados de predicción relacionados con torneos de fútbol reales y competir prediciendo resultados de partidos.",
    "terms.section1.point2": "La App es solo para entretenimiento. No involucra apuestas, juego o apuestas con dinero real.",
    "terms.section1.point3": "La App es soportada por anuncios mostrados a través de Google Mobile Ads (AdMob). Al usar la App reconoces que pueden mostrarse anuncios y que los datos relacionados con la publicidad pueden ser procesados por Google y sus socios publicitarios como se describe en la Política de Privacidad.",
    "terms.section2.title": "2. Cuentas de Usuario",
    "terms.section2.point1": "Se requiere información de registro precisa",
    "terms.section2.point2": "Se requiere verificación de correo electrónico",
    "terms.section2.point3": "Eres responsable de la seguridad de la cuenta",
    "terms.section2.point4": "No se permite compartir cuentas",
    "terms.section2.point5": "Podemos suspender o cancelar cuentas por violaciones",
    "terms.section3.title": "3. Pools y Administración",
    "terms.section3.point1": "Los pools son privados y se accede mediante códigos de invitación",
    "terms.section3.point2": "Los administradores de pools pueden gestionar miembros",
    "terms.section3.point3": "No somos responsables de disputas entre miembros del pool",
    "terms.section4.title": "4. Predicciones y Puntuación",
    "terms.section4.point1": "Las predicciones deben enviarse antes del inicio del partido",
    "terms.section4.point2": "Las predicciones se bloquean al inicio",
    "terms.section4.point3": "La puntuación es automática",
    "terms.section4.point4": "Los resultados de los partidos se basan en marcadores finales oficiales (tiempo extra incluido, penales excluidos)",
    "terms.section4.point5": "Las decisiones de puntuación son finales",
    "terms.section5.title": "5. Uso Justo",
    "terms.section5.point1": "No eludir bloqueos de predicción",
    "terms.section5.point2": "No explotar errores",
    "terms.section5.point3": "No abusar de mecánicas de pool o códigos de invitación",
    "terms.section5.point4": "No interferir con servicios backend",
    "terms.section5.point5": "Las violaciones pueden resultar en suspensión o cancelación",
    "terms.section6.title": "6. APIs de Terceros y Datos Externos",
    "terms.section6.desc": "La App depende de APIs y servicios de terceros para proporcionar datos de partidos, equipos, jugadores e información relacionada, así como otras funciones (por ejemplo autenticación, envío de correo o publicidad). El correcto funcionamiento de la App—incluyendo la carga de datos, la puntuación, las clasificaciones y las notificaciones—depende de la disponibilidad, el rendimiento y la estabilidad de esos servicios de terceros. Interrupciones, límites de uso, errores o cambios por parte de los proveedores pueden causar retrasos, datos incompletos o pérdida temporal de funcionalidad. No garantizamos la exactitud, la puntualidad ni la disponibilidad ininterrumpida de los datos o servicios de terceros.",
    "terms.section7.title": "7. Disponibilidad",
    "terms.section7.desc": "Servicio proporcionado 'según disponibilidad'. No hay garantía de servicio ininterrumpido o sin errores.",
    "terms.section8.title": "8. Propiedad Intelectual",
    "terms.section8.desc": "Todo el contenido, marca, diseños y software son propiedad de BIGTHOR DEVELOPMENT. Prohibida la copia no autorizada o ingeniería inversa.",
    "terms.section9.title": "9. Limitación de Responsabilidad",
    "terms.section9.desc": "La App se proporciona 'tal cual'. No somos responsables de predicciones perdidas, clasificaciones incorrectas o disputas de usuarios. Responsabilidad limitada según lo permitido por la ley.",
    "terms.section10.title": "10. Cancelación",
    "terms.section10.desc": "Puedes eliminar tu cuenta en cualquier momento. Podemos suspender o cancelar por violaciones o mal uso.",
    "terms.section11.title": "11. Ley Aplicable",
    "terms.section11.desc": "Leyes de la Provincia de Quebec y leyes federales aplicables de Canadá.",
    "terms.section12.title": "12. Contacto",
    "terms.section12.desc": "BIGTHOR DEVELOPMENT — Correo electrónico:",

    // Privacy
    "privacy.title": "Política de Privacidad",
    "privacy.updated": "Última actualización: 7 de mayo de 2026",
    "privacy.owner": "BIGTHOR DEVELOPMENT",
    "privacy.intro": "Esta Política de Privacidad explica cómo BIGTHOR DEVELOPMENT recopila, usa, almacena y protege tu información cuando usas la aplicación móvil Matchpool. Usamos tu información para proporcionar las funciones principales de Matchpool y mejorar tu experiencia en la app.",
    "privacy.section1.title": "1. Información que Recopilamos",
    "privacy.section1.point1": "Información de cuenta: nombre, correo electrónico, detalles de perfil, contraseña encriptada (inicio de sesión con correo/contraseña) e identificador de cuenta de Google (si usas Inicio de Sesión con Google)",
    "privacy.section1.point2": "Datos de uso: pools creados o unidos, predicciones enviadas, interacciones de partidos, clasificaciones y puntuaciones, pantallas vistas, acciones realizadas y registros de errores",
    "privacy.section1.point3": "Datos técnicos: tipo de dispositivo y SO, versión de la app, idioma, dirección IP aproximada, eventos en la app y datos de rendimiento",
    "privacy.section1.point4": "Identificadores publicitarios: el ID de Publicidad utilizado por Google Mobile Ads (AdMob) para mostrar y medir anuncios",
    "privacy.section1.point5": "No recopilamos datos personales sensibles como identificaciones gubernamentales, detalles de pago o ubicación precisa",
    "privacy.section2.title": "2. Cómo Usamos tu Información",
    "privacy.section2.desc": "Cuando creas una cuenta o inicias sesión, procesamos datos como tu nombre, correo electrónico y detalles de perfil para autenticarte, mantenerte conectado y permitirte crear o unirte a partidos, gestionar tu perfil y acceder a las funciones de la app. También usamos datos de uso de la app (como pantallas vistas, acciones realizadas y registros de errores) para diagnosticar problemas, mejorar la estabilidad, mejorar funciones, generar clasificaciones y estadísticas, enviar correos transaccionales y detectar abuso. No vendemos tu información personal.",
    "privacy.section3.title": "3. Correos y Notificaciones",
    "privacy.section3.desc": "Verificación de correo (código de 6 dígitos), restablecimiento de contraseña, recordatorios de partidos (solo si no se envió predicción). Sin correos de marketing sin consentimiento explícito.",
    "privacy.section4.title": "4. Publicidad y Anuncios Móviles (AdMob)",
    "privacy.section4.desc": "Matchpool integra Google Mobile Ads (AdMob) para mostrar anuncios. AdMob puede recopilar y usar identificadores de dispositivo como el ID de Publicidad, junto con información técnica (por ejemplo, dirección IP aproximada, tipo de dispositivo, idioma, eventos en la app y datos de rendimiento) para mostrar anuncios, medir el rendimiento de los anuncios, prevenir fraude y abuso, y generar análisis e informes. Esta información puede ser procesada por Google y sus socios publicitarios según sus políticas. Para más detalles, consulta la Política de Privacidad de Google y las políticas de AdMob. Cuando corresponda, puedes restablecer o limitar tu ID de Publicidad desde la configuración de tu dispositivo.",
    "privacy.section5.title": "5. Compartir Datos",
    "privacy.section5.desc": "No vendemos tu información personal. Solo la compartimos con proveedores de servicios necesarios para operar la app — como socios publicitarios (Google AdMob), proveedores de entrega de correo, proveedores de API de datos de fútbol y servicios de infraestructura — o cuando sea requerido por la ley.",
    "privacy.section6.title": "6. Almacenamiento y Seguridad de Datos",
    "privacy.section6.desc": "Datos en base de datos segura; contraseñas hasheadas; tokens con tiempo limitado; acceso basado en roles; salvaguardas razonables aplicadas.",
    "privacy.section7.title": "7. Retención de Datos",
    "privacy.section7.desc": "Datos de cuenta retenidos mientras están activos; puedes solicitar eliminación; algunos datos anonimizados/agregados pueden retenerse.",
    "privacy.section8.title": "8. Tus Derechos",
    "privacy.section8.desc": "Acceso, corrección, eliminación, retirar consentimiento. Contáctanos para solicitudes.",
    "privacy.section9.title": "9. Privacidad de Menores",
    "privacy.section9.desc": "La App no está destinada a usuarios menores de 13 años. No recopilamos datos de menores a sabiendas.",
    "privacy.section10.title": "10. Cambios a Esta Política",
    "privacy.section10.desc": "La política puede actualizarse. La fecha de 'Última actualización' cambiará.",
    "privacy.section11.title": "11. Contacto",
    "privacy.section11.desc": "BIGTHOR DEVELOPMENT — Correo electrónico:",

    // Contact
    "contact.title": "Contáctanos",
    "contact.subtitle": "¿Tienes preguntas o comentarios? Nos encantaría saber de ti.",
    "contact.email": "Envíanos un correo a",
    "contact.owner": "Propiedad de BIGTHOR DEVELOPMENT",
    "contact.form.name": "Nombre",
    "contact.form.email": "Correo Electrónico",
    "contact.form.message": "Mensaje",
    "contact.form.namePlaceholder": "Tu nombre",
    "contact.form.emailPlaceholder": "tu.correo@ejemplo.com",
    "contact.form.messagePlaceholder": "Cuéntanos qué piensas...",
    "contact.form.submit": "Enviar Mensaje",
    "contact.form.success": "¡Mensaje Enviado!",
    "contact.form.successMessage": "Te responderemos pronto.",

    // Social Competition
    "social.title": "Compite y Comparte con Amigos",
    "social.subtitle": "¡No se trata solo de predicciones, sino de presumir!",
    "social.description": "Ve dónde te ubicas contra tus amigos en tiempo real. Comparte tus victorias cuando estés en la cima, o desafíate a escalar de nuevo cuando estés atrás. ¡Cada predicción cuenta!",
    "social.first.title": "En la Cima del Mundo",
    "social.first.description": "Cuando eres #1, ¡hazles saber a todos! Comparte tu racha ganadora.",
    "social.last.title": "Hora de una Revancha",
    "social.last.description": "¿Último lugar? No te preocupes, el próximo partido es tu oportunidad de subir!",
    "social.shareFeature": "¡Comparte tu clasificación con amigos y mantén viva la competencia!",

    // Footer
    "footer.tagline": "Únete a pools, predice marcadores, escala en las clasificaciones.",
    "footer.quickLinks": "Enlaces Rápidos",
    "footer.legal": "Legal",
    "footer.rights": "© 2026 Matchpool por BIGTHOR DEVELOPMENT. Todos los derechos reservados.",
    "footer.entertainment": "Solo para entretenimiento. Sin apuestas o juego con dinero real.",

    // Points Page
    "points.title": "Cómo Se Calculan los Puntos",
    "points.subtitle": "Entiende el sistema de puntuación para maximizar tus predicciones y escalar en las clasificaciones",
    
    "points.overview.title": "Resumen",
    "points.overview.description": "Cada predicción gana puntos a través de un proceso de tres pasos: (1) Puntuación Base (escala de 1-10 basada en precisión), (2) Deducción de Monedas (si cambias predicciones después del inicio) y (3) Multiplicador de Etapa (los partidos de eliminación valen el doble). La predicción del ganador del torneo es separada y otorga 30 puntos.",
    
    "points.step1.title": "Paso 1: Puntuación Base (Escala de 1-10)",
    "points.step1.exactScore.title": "Coincidencia de Marcador Exacto",
    "points.step1.exactScore.description": "Predicción perfecta del marcador final",
    "points.step1.exactScore.example": "Ejemplo: Predices 2-1, resultado es 2-1 → 5 puntos",
    "points.step1.correctResult.title": "Resultado Correcto",
    "points.step1.correctResult.description": "Ganador correcto o empate (pero marcador incorrecto)",
    "points.step1.correctResult.example": "Ejemplo: Predices 2-0, resultado es 3-1 (ambos ganan) → 2 puntos",
    "points.step1.goalDifference.title": "Diferencia de Goles",
    "points.step1.goalDifference.description": "Misma diferencia, no cero y mismo signo",
    "points.step1.goalDifference.example": "Ejemplo: Predices 3-1 (+2), resultado es 2-0 (+2) → 1 punto",
    "points.step1.homeGoal.title": "Conteo de Goles del Equipo Local",
    "points.step1.homeGoal.description": "Goles correctos del equipo local",
    "points.step1.homeGoal.example": "Ejemplo: Predices 2-1, resultado es 2-0 → 1 punto para local",
    "points.step1.awayGoal.title": "Conteo de Goles del Equipo Visitante",
    "points.step1.awayGoal.description": "Goles correctos del equipo visitante",
    "points.step1.awayGoal.example": "Ejemplo: Predices 2-1, resultado es 3-1 → 1 punto para visitante",
    "points.step1.playerEvents.title": "Eventos de Jugadores (Solo Pools Pro)",
    "points.step1.playerEvents.description": "Goleador correcto, asistente, tarjeta amarilla o roja",
    "points.step1.playerEvents.example": "Ejemplo: Predices que Messi anota, Messi anota → 1 punto por evento",
    "points.step1.range.title": "Rango Total de Puntuación Base",
    "points.step1.range.description": "Tu puntuación base varía de 0 a 10 puntos dependiendo de la precisión de la predicción. Los puntos pueden acumularse (el marcador exacto incluye automáticamente el resultado, los goles, etc.).",
    
    "points.step2.title": "Paso 2: Deducción de Monedas (Si Aplica)",
    "points.step2.subtitle": "¿Cambiado Después del Inicio?",
    "points.step2.description": "En pools con monedas, si cambias tu predicción después de que comienza el partido, se deducen puntos de tu puntuación base antes de aplicar el multiplicador de etapa.",
    "points.step2.highScore.title": "Puntuación Base Alta (6-10)",
    "points.step2.highScore.description": "Resta 2 puntos",
    "points.step2.highScore.example": "Ejemplo: 7 puntos base → 7 - 2 = 5 puntos",
    "points.step2.lowScore.title": "Puntuación Base Baja (1-5)",
    "points.step2.lowScore.description": "Resta 1 punto",
    "points.step2.lowScore.example": "Ejemplo: 3 puntos base → 3 - 1 = 2 puntos",
    "points.step2.note.title": "Importante:",
    "points.step2.note.description": "La puntuación nunca baja de 0. Si no se cambia, no se aplica ninguna deducción.",
    
    "points.step3.title": "Paso 3: Multiplicador de Etapa",
    "points.step3.groupStage.title": "Fase de Grupos",
    "points.step3.groupStage.description": "No se aplica multiplicador",
    "points.step3.groupStage.example": "Ejemplo: 5 puntos × 1 = 5 puntos",
    "points.step3.knockout.title": "Fase de Eliminatorias",
    "points.step3.knockout.description": "Los puntos se duplican",
    "points.step3.knockout.example": "Ejemplo: 5 puntos × 2 = 10 puntos",
    
    "points.tournamentWinner.title": "Predicción del Ganador del Torneo",
    "points.tournamentWinner.points": "puntos",
    "points.tournamentWinner.description": "Cuando termina el torneo, cada usuario que predijo correctamente al ganador recibe un bono.",
    "points.tournamentWinner.note.title": "Nota:",
    "points.tournamentWinner.note.description": "No se aplica multiplicador de etapa ni deducción de monedas a este bono.",
    
    "points.example.title": "Cálculo de Ejemplo",
    "points.example.scenario.title": "Escenario:",
    "points.example.scenario.description": "Partido de eliminación. Predices 2-1, lo cambias con monedas. Resultado real: 3-1. Puntuación base: 5 puntos (resultado correcto + goles locales + goles visitantes).",
    "points.example.calculation.title": "Cálculo:",
    "points.example.calculation.step1": "Puntuación Base: Resultado correcto (2) + goles visitantes (1) + diferencia de goles correcta (1) + equipo local ganó (incluido en resultado)",
    "points.example.calculation.step1Result": "Puntuación Base = 4 puntos",
    "points.example.calculation.step2": "Deducción de Monedas: Base es 4 (rango bajo), así que resta 1",
    "points.example.calculation.step2Result": "Después de Deducción = 3 puntos",
    "points.example.calculation.step3": "Multiplicador de Etapa: Fase de Eliminatorias, multiplica por 2",
    "points.example.calculation.step3Result": "Puntos Finales = 3 × 2 = 6 puntos",
    "points.example.final.title": "Puntuación Final:",
    "points.example.final.result": "6 puntos",
    
    "points.poolTypes.title": "Cómo los Tipos de Pools Afectan la Puntuación",
    "points.poolTypes.regular.title": "Pools Regulares",
    "points.poolTypes.regular.feature1": "Solo puntos basados en marcadores",
    "points.poolTypes.regular.feature2": "Sin predicciones de eventos de jugadores",
    "points.poolTypes.pro.title": "Pools Pro",
    "points.poolTypes.pro.feature1": "Puntos basados en marcadores",
    "points.poolTypes.pro.feature2": "+ Eventos de jugadores (goleadores, asistencias, tarjetas)",
    "points.poolTypes.coins.title": "Pools con Monedas",
    "points.poolTypes.coins.feature1": "Puedes cambiar predicciones después del inicio",
    "points.poolTypes.coins.feature2": "Deducción de monedas se aplica antes del multiplicador de etapa",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("matchpool-language");
    return (saved === "en" ? "en" : "es") as Language;
  });

  const toggleLanguage = () => {
    setLanguage((prev) => {
      const newLang = prev === "en" ? "es" : "en";
      localStorage.setItem("matchpool-language", newLang);
      return newLang;
    });
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}